// Generated register defines for conv1d_control

#ifndef _CONV1D_CONTROL_REG_DEFS_
#define _CONV1D_CONTROL_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define CONV1D_CONTROL_PARAM_REG_WIDTH 32

// Accelerator main control configuration
#define CONV1D_CONTROL_CONTROL_REG_OFFSET 0x0
#define CONV1D_CONTROL_CONTROL_START_BIT 0
#define CONV1D_CONTROL_CONTROL_TILE_SIZE_MASK 0x7f
#define CONV1D_CONTROL_CONTROL_TILE_SIZE_OFFSET 1
#define CONV1D_CONTROL_CONTROL_TILE_SIZE_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_CONTROL_TILE_SIZE_MASK, .index = CONV1D_CONTROL_CONTROL_TILE_SIZE_OFFSET })
#define CONV1D_CONTROL_CONTROL_INPUT_CH_MASK 0x3f
#define CONV1D_CONTROL_CONTROL_INPUT_CH_OFFSET 8
#define CONV1D_CONTROL_CONTROL_INPUT_CH_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_CONTROL_INPUT_CH_MASK, .index = CONV1D_CONTROL_CONTROL_INPUT_CH_OFFSET })
#define CONV1D_CONTROL_CONTROL_KERNEL_LEN_MASK 0xf
#define CONV1D_CONTROL_CONTROL_KERNEL_LEN_OFFSET 14
#define CONV1D_CONTROL_CONTROL_KERNEL_LEN_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_CONTROL_KERNEL_LEN_MASK, .index = CONV1D_CONTROL_CONTROL_KERNEL_LEN_OFFSET })

// Memory Buffer Start Addresses (Word Indices 0-127)
#define CONV1D_CONTROL_POINTERS_REG_OFFSET 0x4
#define CONV1D_CONTROL_POINTERS_INPUT_PTR_MASK 0x7f
#define CONV1D_CONTROL_POINTERS_INPUT_PTR_OFFSET 0
#define CONV1D_CONTROL_POINTERS_INPUT_PTR_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_POINTERS_INPUT_PTR_MASK, .index = CONV1D_CONTROL_POINTERS_INPUT_PTR_OFFSET })
#define CONV1D_CONTROL_POINTERS_WEIGHT_PTR_MASK 0x7f
#define CONV1D_CONTROL_POINTERS_WEIGHT_PTR_OFFSET 8
#define CONV1D_CONTROL_POINTERS_WEIGHT_PTR_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_POINTERS_WEIGHT_PTR_MASK, .index = CONV1D_CONTROL_POINTERS_WEIGHT_PTR_OFFSET })
#define CONV1D_CONTROL_POINTERS_OUTPUT_PTR_MASK 0x7f
#define CONV1D_CONTROL_POINTERS_OUTPUT_PTR_OFFSET 16
#define CONV1D_CONTROL_POINTERS_OUTPUT_PTR_FIELD \
  ((bitfield_field32_t) { .mask = CONV1D_CONTROL_POINTERS_OUTPUT_PTR_MASK, .index = CONV1D_CONTROL_POINTERS_OUTPUT_PTR_OFFSET })

// Accelerator status register
#define CONV1D_CONTROL_STATUS_REG_OFFSET 0x8
#define CONV1D_CONTROL_STATUS_RUNNING_BIT 0
#define CONV1D_CONTROL_STATUS_DONE_BIT 1

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _CONV1D_CONTROL_REG_DEFS_
// End generated register defines for conv1d_control
