// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module conv1d_control_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 4
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output conv1d_control_reg_pkg::conv1d_control_reg2hw_t reg2hw, // Write
  input  conv1d_control_reg_pkg::conv1d_control_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import conv1d_control_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic control_start_qs;
  logic control_start_wd;
  logic control_start_we;
  logic [6:0] control_tile_size_qs;
  logic [6:0] control_tile_size_wd;
  logic control_tile_size_we;
  logic [5:0] control_input_ch_qs;
  logic [5:0] control_input_ch_wd;
  logic control_input_ch_we;
  logic [3:0] control_kernel_len_qs;
  logic [3:0] control_kernel_len_wd;
  logic control_kernel_len_we;
  logic [6:0] pointers_input_ptr_qs;
  logic [6:0] pointers_input_ptr_wd;
  logic pointers_input_ptr_we;
  logic [6:0] pointers_weight_ptr_qs;
  logic [6:0] pointers_weight_ptr_wd;
  logic pointers_weight_ptr_we;
  logic [6:0] pointers_output_ptr_qs;
  logic [6:0] pointers_output_ptr_wd;
  logic pointers_output_ptr_we;
  logic status_running_qs;
  logic status_running_wd;
  logic status_running_we;
  logic status_done_qs;
  logic status_done_wd;
  logic status_done_we;

  // Register instances
  // R[control]: V(False)

  //   F[start]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_start (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_start_we),
    .wd     (control_start_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.start.q ),

    // to register interface (read)
    .qs     (control_start_qs)
  );


  //   F[tile_size]: 7:1
  prim_subreg #(
    .DW      (7),
    .SWACCESS("RW"),
    .RESVAL  (7'h0)
  ) u_control_tile_size (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_tile_size_we),
    .wd     (control_tile_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.tile_size.q ),

    // to register interface (read)
    .qs     (control_tile_size_qs)
  );


  //   F[input_ch]: 13:8
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RW"),
    .RESVAL  (6'h0)
  ) u_control_input_ch (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_input_ch_we),
    .wd     (control_input_ch_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.input_ch.q ),

    // to register interface (read)
    .qs     (control_input_ch_qs)
  );


  //   F[kernel_len]: 17:14
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_control_kernel_len (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_kernel_len_we),
    .wd     (control_kernel_len_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.kernel_len.q ),

    // to register interface (read)
    .qs     (control_kernel_len_qs)
  );


  // R[pointers]: V(False)

  //   F[input_ptr]: 6:0
  prim_subreg #(
    .DW      (7),
    .SWACCESS("RW"),
    .RESVAL  (7'h0)
  ) u_pointers_input_ptr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pointers_input_ptr_we),
    .wd     (pointers_input_ptr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pointers.input_ptr.q ),

    // to register interface (read)
    .qs     (pointers_input_ptr_qs)
  );


  //   F[weight_ptr]: 14:8
  prim_subreg #(
    .DW      (7),
    .SWACCESS("RW"),
    .RESVAL  (7'h0)
  ) u_pointers_weight_ptr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pointers_weight_ptr_we),
    .wd     (pointers_weight_ptr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pointers.weight_ptr.q ),

    // to register interface (read)
    .qs     (pointers_weight_ptr_qs)
  );


  //   F[output_ptr]: 22:16
  prim_subreg #(
    .DW      (7),
    .SWACCESS("RW"),
    .RESVAL  (7'h0)
  ) u_pointers_output_ptr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pointers_output_ptr_we),
    .wd     (pointers_output_ptr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pointers.output_ptr.q ),

    // to register interface (read)
    .qs     (pointers_output_ptr_qs)
  );


  // R[status]: V(False)

  //   F[running]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_status_running (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (status_running_we),
    .wd     (status_running_wd),

    // from internal hardware
    .de     (hw2reg.status.running.de),
    .d      (hw2reg.status.running.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.status.running.q ),

    // to register interface (read)
    .qs     (status_running_qs)
  );


  //   F[done]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_status_done (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (status_done_we),
    .wd     (status_done_wd),

    // from internal hardware
    .de     (hw2reg.status.done.de),
    .d      (hw2reg.status.done.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.status.done.q ),

    // to register interface (read)
    .qs     (status_done_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CONV1D_CONTROL_CONTROL_OFFSET);
    addr_hit[1] = (reg_addr == CONV1D_CONTROL_POINTERS_OFFSET);
    addr_hit[2] = (reg_addr == CONV1D_CONTROL_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CONV1D_CONTROL_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(CONV1D_CONTROL_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(CONV1D_CONTROL_PERMIT[2] & ~reg_be)))));
  end

  assign control_start_we = addr_hit[0] & reg_we & !reg_error;
  assign control_start_wd = reg_wdata[0];

  assign control_tile_size_we = addr_hit[0] & reg_we & !reg_error;
  assign control_tile_size_wd = reg_wdata[7:1];

  assign control_input_ch_we = addr_hit[0] & reg_we & !reg_error;
  assign control_input_ch_wd = reg_wdata[13:8];

  assign control_kernel_len_we = addr_hit[0] & reg_we & !reg_error;
  assign control_kernel_len_wd = reg_wdata[17:14];

  assign pointers_input_ptr_we = addr_hit[1] & reg_we & !reg_error;
  assign pointers_input_ptr_wd = reg_wdata[6:0];

  assign pointers_weight_ptr_we = addr_hit[1] & reg_we & !reg_error;
  assign pointers_weight_ptr_wd = reg_wdata[14:8];

  assign pointers_output_ptr_we = addr_hit[1] & reg_we & !reg_error;
  assign pointers_output_ptr_wd = reg_wdata[22:16];

  assign status_running_we = addr_hit[2] & reg_we & !reg_error;
  assign status_running_wd = reg_wdata[0];

  assign status_done_we = addr_hit[2] & reg_we & !reg_error;
  assign status_done_wd = reg_wdata[1];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = control_start_qs;
        reg_rdata_next[7:1] = control_tile_size_qs;
        reg_rdata_next[13:8] = control_input_ch_qs;
        reg_rdata_next[17:14] = control_kernel_len_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[6:0] = pointers_input_ptr_qs;
        reg_rdata_next[14:8] = pointers_weight_ptr_qs;
        reg_rdata_next[22:16] = pointers_output_ptr_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = status_running_qs;
        reg_rdata_next[1] = status_done_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module conv1d_control_reg_top_intf
#(
  parameter int AW = 4,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output conv1d_control_reg_pkg::conv1d_control_reg2hw_t reg2hw, // Write
  input  conv1d_control_reg_pkg::conv1d_control_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  conv1d_control_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


