// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package conv1d_control_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } start;
    struct packed {
      logic [6:0]  q;
    } tile_size;
    struct packed {
      logic [5:0]  q;
    } input_ch;
    struct packed {
      logic [3:0]  q;
    } kernel_len;
  } conv1d_control_reg2hw_control_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } input_ptr;
    struct packed {
      logic [6:0]  q;
    } weight_ptr;
    struct packed {
      logic [6:0]  q;
    } output_ptr;
  } conv1d_control_reg2hw_pointers_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } running;
    struct packed {
      logic        q;
    } done;
  } conv1d_control_reg2hw_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } running;
    struct packed {
      logic        d;
      logic        de;
    } done;
  } conv1d_control_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    conv1d_control_reg2hw_control_reg_t control; // [40:23]
    conv1d_control_reg2hw_pointers_reg_t pointers; // [22:2]
    conv1d_control_reg2hw_status_reg_t status; // [1:0]
  } conv1d_control_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    conv1d_control_hw2reg_status_reg_t status; // [3:0]
  } conv1d_control_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CONV1D_CONTROL_CONTROL_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] CONV1D_CONTROL_POINTERS_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] CONV1D_CONTROL_STATUS_OFFSET = 4'h 8;

  // Register index
  typedef enum int {
    CONV1D_CONTROL_CONTROL,
    CONV1D_CONTROL_POINTERS,
    CONV1D_CONTROL_STATUS
  } conv1d_control_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CONV1D_CONTROL_PERMIT [3] = '{
    4'b 0111, // index[0] CONV1D_CONTROL_CONTROL
    4'b 0111, // index[1] CONV1D_CONTROL_POINTERS
    4'b 0001  // index[2] CONV1D_CONTROL_STATUS
  };

endpackage

